language: ruby
rvm:
- 2.4.1
- 2.5.1
- 2.6.1
- jruby-9.2.5.0
cache: bundler
addons:
  apt:
    packages:
    - libsodium-dev
before_install:
  - gem update --system
  - gem install bundler -v 2.0
script:
  - cd base && bundle exec rake travis && cd ../sdk && LD_LIBRARY_PATH=lib bundle exec rake travis
before_script:
  - cp sdk/spec/config.yml.sample sdk/spec/config.yml
notifications:
  slack:
    secure: D1gWWsjE9i9XLRM6Bfw2pu3tTPW025iqjhgwE3KNw1QwP2TrehbCwRpjVR4rrnaju9FhYqM0+eT4rFc9g6itBPf2pfN1WziVf/CVJORYTzR9HbLL1rMOaWhEv4x/+Uwu0kxQon9ThnM9w6XjjD1+NoBfGn4Lcgc/OgmUGw1jAvQ=
