language: ruby
rvm:
- 2.5.1
- 2.6.2
before_install:
  - sudo add-apt-repository -y ppa:chris-lea/libsodium
  - sudo apt-get -y update
  - sudo apt-get install -y libsodium-dev
  - gem update bundler
script: bundle exec rake travis
notifications:
  slack:
    secure: V/6a8KFe067uukrbCJA2R1HPO4xy0YSQ1pwmHVRi5StX+yl+lYsWWJdjdBdT0j3iJBYyPRqU4bQYck+OloxtELnrHCX+OkodxcxW8W/ACc914iIf0FyY9pnusK7ck2awmt4Iuf94YPgi0XTm1aCcm+f0yU7wiIVFpftoXSk1EDY=
